// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
#pragma once

#include <cstddef>

struct EmbeddedModel {
    const char* op;
    const char* dir;
    const int object_index;
};

extern const EmbeddedModel g_embedded_models[];
extern const std::size_t g_embedded_models_count;
