// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
#pragma once

#include <cstddef>

struct EmbeddedBuffer {
    const unsigned char* data;
    std::size_t size;
};

struct EmbeddedModel {
    const char* op;
    const char* dir;
    const unsigned char* pte_data;
    std::size_t pte_size;
    const EmbeddedBuffer* inputs;
    std::size_t num_inputs;
    const EmbeddedBuffer* expected;
    std::size_t num_outputs;
    float atol;
    float rtol;
};

extern const EmbeddedModel g_embedded_models[];
extern const std::size_t g_embedded_models_count;
