#!/usr/bin/env python3
"""Generates embedded_models.S + embedded_models.cpp + embedded_models.h.

Reads models/manifest.json, walks each model directory, and emits .incbin
assembly directives so model.pte, input_*.bin and expected_*.bin land in
.rodata at link time. No semihosting needed at run-time.

Re-run this whenever models/manifest.json or any model dir changes.

The .incbin paths are emitted RELATIVE to this directory (models/<dir>/<file>);
the cproject's ``add-path: .`` adds the project dir to the assembler search path
so they resolve regardless of the build working directory.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODELS_DIR = HERE / "models"
MANIFEST = MODELS_DIR / "manifest.json"

OUT_S = HERE / "embedded_models.S"
OUT_CPP = HERE / "embedded_models.cpp"
OUT_H = HERE / "embedded_models.h"


def sym(prefix: str, dirname: str, suffix: str = "") -> str:
    name = f"_emb_{prefix}_{dirname}"
    if suffix:
        name = f"{name}_{suffix}"
    return name


def main() -> int:
    with MANIFEST.open() as f:
        manifest = json.load(f)

    s_lines: list[str] = [
        "/* AUTO-GENERATED by gen_embedded_models.py -- do not edit. */",
        "    .section .rodata.embedded_models,\"a\",%progbits",
        "    .balign 16",
        "",
    ]
    cpp_lines: list[str] = [
        "// AUTO-GENERATED by gen_embedded_models.py -- do not edit.",
        "#include \"embedded_models.h\"",
        "",
        "extern \"C\" {",
    ]
    manifest_entries: list[str] = []

    for entry in manifest:
        d = entry["dir"]
        op = entry["op"]
        atol = float(entry.get("atol", 1e-3))
        rtol = float(entry.get("rtol", 1e-3))
        model_dir = MODELS_DIR / d
        pte = model_dir / "model.pte"
        if not pte.exists():
            print(f"warning: missing {pte}", file=sys.stderr)
            continue

        # Assembly: .incbin per binary file, with start/end labels.
        def emit(prefix: str, path: Path, suffix: str = ""):
            s = sym(prefix, d, suffix)
            s_lines.extend([
                f"    .balign 16",
                f"    .global {s}_start",
                f"{s}_start:",
                f"    .incbin \"{path.relative_to(HERE).as_posix()}\"",
                f"    .global {s}_end",
                f"{s}_end:",
                "",
            ])
            cpp_lines.extend([
                f"extern const unsigned char {s}_start[];",
                f"extern const unsigned char {s}_end[];",
            ])

        emit("pte", pte)
        for i, inp in enumerate(entry.get("inputs", [])):
            p = model_dir / inp["file"]
            if not p.exists():
                print(f"warning: missing input {p}", file=sys.stderr)
                continue
            emit("in", p, f"{i}")
        for i, out in enumerate(entry.get("outputs", [])):
            p = model_dir / out["file"]
            if not p.exists():
                print(f"warning: missing expected {p}", file=sys.stderr)
                continue
            emit("exp", p, f"{i}")

        n_inputs = len(entry.get("inputs", []))
        n_outputs = len(entry.get("outputs", []))

        # Per-model input / expected arrays.
        cpp_lines.append("}  // extern \"C\"")
        cpp_lines.append("")
        cpp_lines.append(f"static const EmbeddedBuffer kInputs_{d}[] = {{")
        for i in range(n_inputs):
            s = sym("in", d, str(i))
            cpp_lines.append(
                f"    {{ {s}_start, static_cast<std::size_t>({s}_end - {s}_start) }},"
            )
        cpp_lines.append("};")
        cpp_lines.append(f"static const EmbeddedBuffer kExpected_{d}[] = {{")
        for i in range(n_outputs):
            s = sym("exp", d, str(i))
            cpp_lines.append(
                f"    {{ {s}_start, static_cast<std::size_t>({s}_end - {s}_start) }},"
            )
        cpp_lines.append("};")
        cpp_lines.append("extern \"C\" {")

        pte_s = sym("pte", d)
        manifest_entries.append(
            f"    {{ \"{op}\", \"{d}\",\n"
            f"      {pte_s}_start, static_cast<std::size_t>({pte_s}_end - {pte_s}_start),\n"
            f"      kInputs_{d}, {n_inputs},\n"
            f"      kExpected_{d}, {n_outputs},\n"
            f"      {atol}f, {rtol}f }},"
        )

    cpp_lines.append("}  // extern \"C\"")
    cpp_lines.append("")
    cpp_lines.append("const EmbeddedModel g_embedded_models[] = {")
    cpp_lines.extend(manifest_entries)
    cpp_lines.append("};")
    cpp_lines.append("")
    cpp_lines.append(
        "const std::size_t g_embedded_models_count = "
        "sizeof(g_embedded_models) / sizeof(g_embedded_models[0]);"
    )
    cpp_lines.append("")

    h_lines = [
        "// AUTO-GENERATED by gen_embedded_models.py -- do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "struct EmbeddedBuffer {",
        "    const unsigned char* data;",
        "    std::size_t size;",
        "};",
        "",
        "struct EmbeddedModel {",
        "    const char* op;",
        "    const char* dir;",
        "    const unsigned char* pte_data;",
        "    std::size_t pte_size;",
        "    const EmbeddedBuffer* inputs;",
        "    std::size_t num_inputs;",
        "    const EmbeddedBuffer* expected;",
        "    std::size_t num_outputs;",
        "    float atol;",
        "    float rtol;",
        "};",
        "",
        "extern const EmbeddedModel g_embedded_models[];",
        "extern const std::size_t g_embedded_models_count;",
        "",
    ]

    OUT_S.write_text("\n".join(s_lines))
    OUT_CPP.write_text("\n".join(cpp_lines))
    OUT_H.write_text("\n".join(h_lines))

    total = sum(p.stat().st_size for p in MODELS_DIR.rglob("*.pte"))
    total += sum(p.stat().st_size for p in MODELS_DIR.rglob("*.bin"))
    print(f"embedded {total:,} bytes across {len(manifest)} models")
    print(f"wrote {OUT_S.relative_to(HERE)}, {OUT_CPP.relative_to(HERE)}, "
          f"{OUT_H.relative_to(HERE)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
