#!/usr/bin/env python3
# Copyright 2026 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
"""Embed the per-op test models into the all-ops firmware.

Reads ``models/manifest.json`` (produced by generate_test_models.py) and emits
three sources the consumer build compiles in:

  * embedded_models_blob.S  -- ``.incbin`` of each model.pte / input_*.bin /
    expected_*.bin into .rodata, so the image is self-contained and needs no
    semihosting filesystem access at run time. (The ``.S`` stem is distinct
    from embedded_models.cpp to avoid AC6's cbuild2cmake object-name clash.)
  * embedded_models.cpp     -- the g_embedded_models[] table referencing the
    blob symbols, plus per-model input/expected arrays.
  * embedded_models.h       -- the EmbeddedModel/EmbeddedBuffer structs.

The ``.incbin`` paths are RELATIVE to this directory (``models/<dir>/<file>``).
The consumer project carries ``add-path: [.]`` -> ``-I<project-dir>``, which the
assembler searches for ``.incbin``, so the same generated file resolves whether
the build runs on the host or inside the Docker build container (host absolute
paths would not exist in the container).

If ``models/manifest.json`` is absent (build/link-coverage only, no torch
export step), a valid empty stub is emitted so the image still links and runs
(reporting 0/0). Re-run whenever the manifest or any model dir changes.

"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
import container

_HERE = Path(__file__).resolve().parent


# A 1-element dummy array (never indexed: count is 0) keeps g_embedded_models a
# well-formed definition when no models are embedded -- C++ has no zero-length
# arrays.
_CPP_STUB = """\
// AUTO-GENERATED by gen_embedded_models.py -- do not edit.
// Stub: no models/manifest.json found (build/link coverage only).
#include "embedded_models.h"

const EmbeddedModel g_embedded_models[] = {
    { "", "", 0 },
};
const std::size_t g_embedded_models_count = 0;
"""


def build(models_dir: Path, output_dir: Path, base_addr: int) -> tuple[str,int]:
    """Return (blob_s, cpp, header, n_models, n_bytes)."""
    manifest_path = models_dir / "manifest.json"
    if not manifest_path.exists():
        return _CPP_STUB, 0
    
    manifest = json.loads(manifest_path.read_text())
    
    filenames = [(Path("models") / Path(x["name"])).with_suffix(".pte") for x in manifest]
    
    container.generate_container(base_addr,filenames, output_dir / "container.bin")

    # Force rebuilds that do not track .incbin dependencies inside the assembly.
    (output_dir / "embedded_models_blob.S").touch()

    cpp_lines = [
        "// AUTO-GENERATED by gen_embedded_models.py -- do not edit.",
        '#include "embedded_models.h"',
        "",
    ]

    cpp_lines.append(f"const std::size_t g_embedded_models_count = {len(manifest)};\n")
    cpp_lines.append("const EmbeddedModel g_embedded_models[]={")
    for i, model in enumerate(manifest):
        cpp_lines.append(f'    {{ "{model["op"]}", "{model["name"]}", {i} }},')

    cpp_lines.append("}; /* end of g_embedded_models */;")

    return "\n".join(cpp_lines), len(manifest)
   


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Embed per-op test models into the all-ops firmware"
    )
    parser.add_argument(
        "--models-dir",
        default=str(_HERE / "models"),
        help="directory with per-op model dirs + manifest.json",
    )
    # We don't always know the final base addr. This address just need to be aligned as the
    # runtime base address. The container is only using offsets relative to this base address
    parser.add_argument(
        "--base_addr",
        default="0x0",
        help="hexadecimal base address for the container (must be aligned as the runtime base address)",
    )
    parser.add_argument(
        "--output-dir",
        default=str(_HERE),
        help="where to write embedded_models.{h,cpp,_blob.S}",
    )
    args = parser.parse_args()

    models_dir = Path(args.models_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    cpp, nb_models = build(models_dir, output_dir,int(args.base_addr, 16))

    (output_dir / "embedded_models.cpp").write_text(cpp)

    if nb_models:
        print(f"{nb_models} models -> {output_dir}")
    else:
        print(f"no models/manifest.json under {models_dir}: wrote empty stub")
    return 0


if __name__ == "__main__":
    sys.exit(main())
