/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p9-g859cb6c9
 *
 * Project: 'all_ops.Debug+ARMCM55' 
 * Target:  'Debug+ARMCM55' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* PyTorch::Machine Learning:ExecuTorch:Runtime@1.3.1-rc9 */
/* ExecuTorch global configuration */
        #define C10_USING_CUSTOM_GENERATED_MACROS
        #define FLATBUFFERS_MAX_ALIGNMENT 1024
        #define FLATBUFFERS_LOCALE_INDEPENDENT 0


#endif /* PRE_INCLUDE_GLOBAL_H */
